### ISSUE TITLE
Ne radi ispravno !

### ISSUE THREAD

**Issue by mozgy** [e-radionicacom/Croduino-NOVA-Eagle-Files#1]
Pozdrav,

primih jedan primjerak (Chip ID: 495350) ali ne radi ispravno, cijelo vrijeme je u bootloader modu.

**Comment by davidzovko** [comment]
Kratki spoj ispod GPIO_SW - spojen GPIO0 s groundom pa pločica automatski odlazi u boot mode. Ispravljeno na v1.1. 

Fix za ovu verziju je prerezati trace prikazan na slici. Nakon toga sve radi odlično. 
![trace1](https://cloud.githubusercontent.com/assets/12273484/13334546/b69097d8-dc0c-11e5-9b8e-c58d02308362.jpg)
